In [1]:
import pandas as pd
df = pd.read_csv('pong.csv')
df.head()

     x    y  vx  vy  objet_raquette_2
0  490  290   3   3               250
1  493  293   3   3               250
2  496  296   3   3               250
3  499  299   3   3               250
4  502  302   3   3               250

In [2]:
df.describe()

,x,y,vx,vy,objet_raquette_2
count,20245.000000,20245.000000,20245.000000,20245.000000,20245.000000
mean,475.451519,284.187898,-0.129365,-0.008150,245.795011
std,253.356228,107.729678,2.997283,3.000063,75.846904
min,-32.000000,98.000000,-3.000000,-3.000000,110.000000
25%,256.000000,191.000000,-3.000000,-3.000000,180.000000
50%,475.000000,284.000000,-3.000000,-3.000000,240.000000
75%,694.000000,377.000000,3.000000,3.000000,300.000000
max,1003.000000,470.000000,3.000000,3.000000,400.000000

In [3]:
df = df.drop_duplicates()
df.describe()

,x,y,vx,vy,objet_raquette_2
count,18032.000000,18032.000000,18032.000000,18032.000000,18032.000000
mean,473.077085,284.848492,-0.028283,0.006322,246.390306
std,251.916810,107.916749,2.999950,3.000077,74.760611
min,-32.000000,98.000000,-3.000000,-3.000000,110.000000
25%,259.000000,191.000000,-3.000000,-3.000000,190.000000
50%,469.000000,284.000000,-3.000000,3.000000,240.000000
75%,688.000000,380.000000,3.000000,3.000000,300.000000
max,1003.000000,470.000000,3.000000,3.000000,400.000000

In [4]:
x = df.drop(columns="objet_raquette_2")
y = df["objet_raquette_2"]

x.head()

     x    y  vx  vy
0  490  290   3   3
1  493  293   3   3
2  496  296   3   3
3  499  299   3   3
4  502  302   3   3

In [5]:
y.head()

0    250
1    250
2    250
3    250
4    250
Name: objet_raquette_2, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3)

In [8]:
from sklearn.neighbors import KNeighborsRegressor

In [9]:
clt = KNeighborsRegressor(n_neighbors=4)
clt.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=4)

In [10]:
y_pred_knn = clt.predict(x_test)

In [11]:
from sklearn.metrics import r2_score

In [12]:
r2_score(y_test, y_pred_knn)

0.7540958065759489

In [13]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(x_train, y_train)

RandomForestRegressor()

In [14]:
y_pred_rfr = rfr.predict(x_test)

In [15]:
r2_score(y_test, y_pred_rfr)

0.8487851016476313